// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ForceUpload(arg1) {
  return window['go']['main']['App']['ForceUpload'](arg1);
}

export function GetRecentTags() {
  return window['go']['main']['App']['GetRecentTags']();
}

export function GetSelectedPhoto() {
  return window['go']['main']['App']['GetSelectedPhoto']();
}

export function ResizeWindow(arg1) {
  return window['go']['main']['App']['ResizeWindow'](arg1);
}

export function Upload(arg1) {
  return window['go']['main']['App']['Upload'](arg1);
}
