// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {types} from '../models';

export function ForceUpload(arg1:main.PhotoMetadata):Promise<main.UploadResult>;

export function GetRecentTags():Promise<Array<string>>;

export function GetSelectedPhoto():Promise<main.PhotoMetadata>;

export function GetSelectedPhotos():Promise<Array<main.PhotoMetadata>>;

export function HandlePullRequest(arg1:string):Promise<void>;

export function PostPullSelection(arg1:types.PullRequest):Promise<main.MultiPhotoUploadResult>;

export function ResizeWindow(arg1:boolean):Promise<void>;

export function StartThumbnailGeneration(arg1:Array<main.PhotoMetadata>):Promise<void>;

export function TestMultiSelect():Promise<string>;

export function Upload(arg1:main.PhotoMetadata):Promise<main.UploadResult>;

export function UploadMultiplePhotos(arg1:main.MultiPhotoUploadRequest):Promise<main.MultiPhotoUploadResult>;
