// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetRecentTags():Promise<Array<string>>;

export function GetSelectedPhoto():Promise<main.PhotoMetadata>;

export function Upload(arg1:main.PhotoMetadata):Promise<main.UploadResult>;
